development:
  adapter: postgresql
  encoding: unicode
  database: repository_app
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: repository_app
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: repository_app
  pool: 5
